name: Build (Nintendo Switch)

on: [push, pull_request]

jobs:
  switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: |
          . /opt/devkitpro/switchvars.sh
          mkdir _build && cd _build
          ../configure --host=aarch64-none-elf \
              --prefix=switch-sdl2 \
              --disable-shared --enable-static \
              --enable-audio \
              --enable-joystick \
              --disable-power \
              --disable-filesystem \
              --enable-cpuinfo \
              --enable-pthreads \
              --enable-timers \ 
              --enable-video
      - name: Build
        run: make -C _build 
      - name: install
        run: make -C _build install
